[package]
name = "libaoc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.14"
colored = "2"
chrono = "0.4"
criterion = "0.3.5"